import {
  LayoutDashboard,
  ReceiptText,
  Landmark,
  UserPlus,
  Library,
  Tag,
  Megaphone,
  ShoppingCart,
  Wallet,
  Package,
  FileText,
  Users,
  Truck,
  Shield,
  ClipboardList,
  PackageOpen,
  Trash2,
  Receipt,
  PackagePlus,
  Undo2,
  ShoppingBag,
  RotateCcw,
  Wrench,
  Bike,
  Activity,
  LayoutList,
  ListChecks,
  Clock,
  Gavel,
  Calculator,
  TrendingUp,
  BarChart2,
  Layers,
  UserSearch,
  Gauge,
  CalendarCheck,
} from 'lucide-react';

export const SIDEBAR_SECTIONS = [
  {
    title: 'Tổng quan',
    items: [{ id: 'overview', label: 'Tổng quan', icon: LayoutDashboard }],
  },
  {
    title: 'Hàng hóa',
    groups: [
      { header: 'Hàng hóa', itemIds: ['goods', 'goods-pricing', 'goods-warranty'] },
      { header: 'Kho hàng', itemIds: ['goods-audit', 'goods-disposal', 'goods-internal-use'] },
    ],
    items: [
      { id: 'goods', label: 'Danh sách hàng hóa', icon: Package },
      { id: 'goods-pricing', label: 'Thiết lập giá', icon: Tag },
      { id: 'goods-warranty', label: 'Bảo hành, bảo trì', icon: Shield },
      { id: 'goods-audit', label: 'Kiểm kho', icon: ClipboardList },
      { id: 'goods-disposal', label: 'Trừ hàng lỗi/hư', icon: Trash2 },
      { id: 'goods-internal-use', label: 'Xuất dùng nội bộ', icon: PackageOpen, badge: 'Mới' },
    ],
  },
  {
    title: 'Mua hàng',
    groups: [
      { header: 'Nhà cung cấp', itemIds: ['suppliers', 'purchase-invoices'] },
      { header: 'Mua hàng', itemIds: ['goods-purchase', 'purchase-returns'] },
    ],
    items: [
      { id: 'suppliers', label: 'Nhà cung cấp', icon: Truck },
      { id: 'purchase-invoices', label: 'Hóa đơn đầu vào', icon: Receipt, badge: 'Mới' },
      { id: 'goods-purchase', label: 'Nhập hàng', icon: PackagePlus },
      { id: 'purchase-returns', label: 'Trả hàng nhập', icon: Undo2 },
    ],
  },
  {
    title: 'Đơn hàng',
    items: [
      { id: 'orders', label: 'Đặt hàng', icon: ShoppingBag },
      { id: 'order-invoices', label: 'Hóa đơn', icon: ReceiptText },
      { id: 'order-returns', label: 'Trả hàng', icon: RotateCcw },
      { id: 'order-repairs', label: 'Yêu cầu sửa chữa', icon: Wrench },
    ],
  },
  {
    title: 'Online',
    items: [
      { id: 'shopee-revenue', label: 'Doanh Thu Shopee', icon: ShoppingCart },
      { id: 'delivery-partners', label: 'Đối tác giao hàng', icon: Bike },
      { id: 'shipping-orders', label: 'Vận đơn', icon: FileText },
    ],
  },
  {
    title: 'Khách hàng',
    items: [{ id: 'customers', label: 'Khách Hàng', icon: Users }],
  },
  {
    title: 'Nhân sự',
    groups: [
      { header: 'Nhân sự', itemIds: ['staff', 'staff-ledger'] },
      {
        header: 'Lương & Thưởng',
        itemIds: [
          'payroll-attendance',
          'payroll-overtime',
          'payroll-sales',
          'payroll-penalties',
          'payroll-summary',
          'payroll-ledger',
        ],
      },
    ],
    items: [
      { id: 'staff', label: 'Danh sách nhân sự', icon: UserPlus },
      { id: 'staff-ledger', label: 'Sổ cái hiệu năng', icon: LayoutList },
      { id: 'payroll-attendance', label: 'Chấm công', icon: ListChecks },
      { id: 'payroll-overtime', label: 'Tăng ca', icon: Clock },
      { id: 'payroll-sales', label: 'Doanh số', icon: TrendingUp },
      { id: 'payroll-penalties', label: 'Các khoản khấu trừ', icon: Gavel },
      { id: 'payroll-summary', label: 'Bảng lương', icon: Calculator },
      { id: 'payroll-ledger', label: 'Sổ cái lương', icon: Landmark },
    ],
  },
  {
    title: 'Sổ quỹ',
    items: [{ id: 'cash-ledger', label: 'Sổ quỹ', icon: Landmark }],
  },
  {
    title: 'Phân tích',
    groups: [
      {
        header: 'Phân tích',
        itemIds: [
          'analysis-business',
          'analysis-online-sales',
          'analysis-goods',
          'analysis-customers',
          'analysis-staff',
          'analysis-expenses',
          'analysis-efficiency',
        ],
      },
      {
        header: 'Báo cáo',
        itemIds: [
          'report-eod',
          'report-sales',
          'report-orders',
          'report-goods',
          'report-customers',
        ],
      },
      {
        header: '',
        itemIds: ['report-suppliers', 'report-staff', 'report-channels', 'report-finance'],
      },
    ],
    items: [
      { id: 'analysis-business', label: 'Kinh Doanh', icon: TrendingUp, badge: 'AI' },
      { id: 'analysis-online-sales', label: 'Bán Online', icon: ShoppingCart, badge: 'AI' },
      { id: 'analysis-goods', label: 'Hàng Hóa', icon: BarChart2, badge: 'AI' },
      { id: 'analysis-customers', label: 'Khách Hàng', icon: UserSearch, badge: 'AI' },
      { id: 'analysis-staff', label: 'Nhân Sự', icon: Activity, badge: 'AI' },
      { id: 'analysis-expenses', label: 'Chi Phí', icon: Wallet },
      { id: 'analysis-efficiency', label: 'Hiệu Quả', icon: Gauge, badge: 'AI' },
      { id: 'report-eod', label: 'Cuối Ngày', icon: CalendarCheck },
      { id: 'report-sales', label: 'Bán Hàng', icon: ShoppingCart },
      { id: 'report-orders', label: 'Đặt Hàng', icon: ShoppingBag },
      { id: 'report-goods', label: 'Hàng Hóa', icon: Package },
      { id: 'report-customers', label: 'Khách Hàng', icon: Users },
      { id: 'report-suppliers', label: 'Nhà Cung Cấp', icon: Truck },
      { id: 'report-staff', label: 'Nhân Viên', icon: UserPlus },
      { id: 'report-channels', label: 'Kênh Bán Hàng', icon: Layers },
      { id: 'report-finance', label: 'Tài Chính', icon: Wallet },
    ],
  },
  {
    title: 'Marketing',
    items: [
      { id: 'promotions', label: 'Khuyến Mãi', icon: Tag },
      { id: 'marketing', label: 'Nội dung Fanpage', icon: Megaphone },
    ],
  },
  {
    title: 'Hệ thống',
    groups: [
      {
        header: 'Hệ thống',
        itemIds: ['sop-mechanisms', 'sop-standards', 'sop-workflows', 'sop-templates'],
      },
    ],
    items: [
      { id: 'sop-mechanisms', label: 'Cơ chế', icon: Library },
      { id: 'sop-standards', label: 'Quy chuẩn', icon: ClipboardList },
      { id: 'sop-workflows', label: 'Quy trình', icon: ListChecks },
      { id: 'sop-templates', label: 'Biểu mẫu', icon: FileText },
    ],
  },
];
